An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Package search: {'_pypi_ordering': False, 'version': '6.0.3', 'name': 'django-facebook', 'summary': 'Facebook open graph API client in python. Enables django applications to register users using facebook.\nFixes issues with the official but unsupported Facebook python-sdk. Enables mobile facebook authentication.\nCanvas page authentication for facebook applications. FQL access via the server side api.'}
Creating standard recipe for django-facebook-6.0.3
Converting recipe in /home/ubuntu/pypi-conda-builds/django-facebook
package = django-facebook
   dependencies = [u'unidecode']
Creating standard recipe for unidecode
Converting recipe in /home/ubuntu/pypi-conda-builds/unidecode
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-pipbuild", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 80, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 349, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 360, in execute
    build_package(package, version, noarch_python=args.noarch_python)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 314, in build_package
    build_package(depend)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 301, in build_package
    noarch_python=noarch_python)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 183, in convert_recipe
    d['homeurl'] = meta['about']['home']
KeyError: 'home'
