Error: prefix already exists: /home/ubuntu/miniconda/envs/_pipbuild_
Collecting gensim==0.11.1-1
  Downloading http://localhost/packages/source/g/gensim/gensim-0.11.1-1.tar.gz (2.2MB)
setuptools must be installed to install from a source distribution
Package search: {'_pypi_ordering': False, 'version': '0.11.1-1', 'name': 'gensim', 'summary': 'Python framework for fast Vector Space Modelling'}
Creating standard recipe for gensim-0.11.1-1
Using url https://pypi.python.org/packages/source/g/gensim/gensim-0.11.1-1.tar.gz (2.1 MB) for gensim.
Downloading gensim
Using cached download
Unpacking gensim...
done
working in /tmp/tmpdCE13gconda_skeleton_gensim-0.11.1-1.tar.gz
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.0. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-1.3.2.tar.gz
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    ez_setup.use_setuptools()
  File "/tmp/tmpdCE13gconda_skeleton_gensim-0.11.1-1.tar.gz/gensim-0.11.1-1/ez_setup.py", line 132, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/tmp/tmpdCE13gconda_skeleton_gensim-0.11.1-1.tar.gz/gensim-0.11.1-1/ez_setup.py", line 110, in _do_download
    to_dir, download_delay)
  File "/tmp/tmpdCE13gconda_skeleton_gensim-0.11.1-1.tar.gz/gensim-0.11.1-1/ez_setup.py", line 290, in download_setuptools
    downloader(url, saveto)
  File "/tmp/tmpdCE13gconda_skeleton_gensim-0.11.1-1.tar.gz/gensim-0.11.1-1/ez_setup.py", line 197, in download_file_curl
    _clean_check(cmd, target)
  File "/tmp/tmpdCE13gconda_skeleton_gensim-0.11.1-1.tar.gz/gensim-0.11.1-1/ez_setup.py", line 160, in _clean_check
    subprocess.check_call(cmd)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['curl', 'https://pypi.python.org/packages/source/s/setuptools/setuptools-1.3.2.tar.gz', '--silent', '--output', '/tmp/tmpdCE13gconda_skeleton_gensim-0.11.1-1.tar.gz/gensim-0.11.1-1/setuptools-1.3.2.tar.gz']' returned non-zero exit status 77

Applying patch: '/tmp/tmpdCE13gconda_skeleton_gensim-0.11.1-1.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpdCE13gconda_skeleton_gensim-0.11.1-1.tar.gz/gensim-0.11.1-1
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install

conda create -n _pipbuild_ --yes python pip
/home/ubuntu/miniconda/envs/_pipbuild_/bin/pip install gensim==0.11.1-1
Error: Could not pip install gensim==0.11.1-1
