Warning, the following versions were found for plone.recipe.zope2instance
4.2.17
4.2.16
4.2.15
4.2.14
4.2.13
4.2.12
4.2.11
4.2.10
4.2.9
4.2.8
4.2.7
4.2.6
4.2.5
4.2.4
4.2.3
4.2.2
4.2.1
4.2
4.1.9
4.1.8
4.1.7
4.1.6
4.1.5
4.1.4
4.1.3
4.1.2
4.1.1
4.1
4.0.5
4.0.4
4.0.3
4.0.2
4.0.1
4.0.0
4.0b2
4.0b1
4.0a4
4.0a3
4.0a2
4.0a1
3.11
3.10
3.9
3.8
3.7
3.6
3.5
3.4
3.3
3.2
3.1
3.0
2.9
2.8
2.7
2.6
2.5
2.4
2.3.1
2.3
2.2
2.1
2.0
1.9
1.8
1.7
1.6
1.5
1.4
1.3
1.2
1.1
1.0
0.9
0.8
0.7
0.6.1
0.6
0.5
0.4
0.3
0.2
0.1
Using 4.2.17
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/p/plone.recipe.zope2instance/plone.recipe.zope2instance-4.2.17.tar.gz (74 KB) for plone.recipe.zope2instance.
Downloading plone.recipe.zope2instance
Using cached download
Unpacking plone.recipe.zope2instance...
done
working in /tmp/tmpwSyoUgconda_skeleton_plone.recipe.zope2instance-4.2.17.tar.gz
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


The following NEW packages will be INSTALLED:

    numpy:      1.9.2-py27_0 
    openssl:    1.0.1k-1     
    pip:        7.0.3-py27_0 
    python:     2.7.10-0     
    pyyaml:     3.11-py27_1  
    readline:   6.2-2        
    setuptools: 18.0.1-py27_0
    sqlite:     3.8.4.1-1    
    system:     5.8-2        
    tk:         8.5.18-0     
    yaml:       0.1.6-0      
    zlib:       1.2.8-0      

Linking packages ...
[                    ]|                                                  |   0%[openssl             ]|                                                  |   0%[readline            ]|####                                              |   8%[sqlite              ]|########                                          |  16%[system              ]|############                                      |  25%[tk                  ]|################                                  |  33%[yaml                ]|####################                              |  41%[zlib                ]|#########################                         |  50%[numpy               ]|#############################                     |  58%[python              ]|#################################                 |  66%[pyyaml              ]|#####################################             |  75%[setuptools          ]|#########################################         |  83%[pip                 ]|#############################################     |  91%[      COMPLETE      ]|##################################################| 100%
Applying patch: '/tmp/tmpwSyoUgconda_skeleton_plone.recipe.zope2instance-4.2.17.tar.gz/pypi-distutils.patch'
zodb3 not found, trying ZODB3
Warning, the following versions were found for ZODB3
3.11.0
3.11.0a3
3.11.0a2
3.11.0a1
3.10.5
3.10.4
3.10.3
3.10.2
3.10.1
3.10.0
3.10.0b8
3.10.0b7
3.10.0b6
3.10.0b5
3.10.0b4
3.10.0b3
3.10.0b2
3.10.0b1
3.10.0a2
3.10.0a1
3.9.7
3.9.6
3.9.5
3.9.4
3.9.3
3.9.2
3.9.1
3.9.0
3.9.0c3
3.9.0c2
3.9.0c1
3.9.0b5
3.9.0b4
3.9.0b3
3.9.0b2
3.9.0b1
3.9.0a12
3.9.0a11
3.9.0a10
3.9.0a9
3.9.0a7
3.9.0a6
3.9.0a5
3.9.0a4
3.9.0a3
3.9.0a2
3.9.0a1
3.8.6
3.8.5
3.8.4
3.8.3
3.8.3b1
3.8.2
3.8.1
3.8.1b9
3.8.1b8
3.8.1b7
3.8.1b6
3.8.1b5
3.8.1b4
3.8.1b3
3.8.1b2
3.8.1b1
3.8.0
3.8.0c1
3.8.0b4
3.8.0b3
3.8.0b2
3.8.0b1
3.8.0a1
3.7.2
3.7.0
3.6.0
3.5.1
3.5.0
3.4.2
3.3.1
3.2.10
3.1.5
Using 3.11.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/Z/ZODB3/ZODB3-3.11.0.tar.gz (54 KB) for ZODB3.
Downloading ZODB3
Using cached download
Unpacking ZODB3...
done
working in /tmp/tmpjoOvT7conda_skeleton_ZODB3-3.11.0.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

Applying patch: '/tmp/tmpjoOvT7conda_skeleton_ZODB3-3.11.0.tar.gz/pypi-distutils.patch'
Error: Could not parse: ZEO [test]
