Warning, the following versions were found for plone.app.upgrade
1.3.10
1.3.9
1.3.8
1.3.7
1.3.6
1.3.5
1.3.4
1.3.3
1.3.2
1.3.1
1.3
1.3rc1
1.3b2
1.3b1
1.3a2
1.3a1
1.2.7
1.2.6
1.2.5
1.2.4
1.2.3
1.2.2
1.2.1
1.2
1.2rc2
1.2rc1
1.2b2
1.2b1
1.2a2
1.2a1
1.1.7
1.1.6
1.1.5
1.1.4
1.1.3
1.1.2
1.1.1
1.1
1.1rc3
1.1rc2
1.1b2
1.1b1
1.1a3
1.1a2
1.1a1
1.0.10
1.0.9
1.0.8
1.0.7
1.0.6
1.0.5
1.0.4
1.0.3
1.0.2
1.0.1
1.0
1.0rc1
1.0b5
1.0b4
1.0b3
1.0b2
1.0b1
1.0a5
1.0a4
1.0a3
1.0a2
1.0a1
Using 1.3.10
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/p/plone.app.upgrade/plone.app.upgrade-1.3.10.zip (1.7 MB) for plone.app.upgrade.
Downloading plone.app.upgrade
Using cached download
Unpacking plone.app.upgrade...
done
working in /tmp/tmpo_JJ5Tconda_skeleton_plone.app.upgrade-1.3.10.zip
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


The following NEW packages will be INSTALLED:

    numpy:  1.9.2-py27_0
    pyyaml: 3.11-py27_1 
    yaml:   0.1.6-0     

Linking packages ...
[                    ]|                                                  |   0%[yaml                ]|                                                  |   0%[numpy               ]|################                                  |  33%[pyyaml              ]|#################################                 |  66%[      COMPLETE      ]|##################################################| 100%
Applying patch: '/tmp/tmpo_JJ5Tconda_skeleton_plone.app.upgrade-1.3.10.zip/pypi-distutils.patch'
WARNING: Could not add entry points. They were:

      [z3c.autoinclude.plugin]
      target = plone
      
Warning, the following versions were found for plone.app.theming
1.2.6
1.2.5
1.2.4
1.2.3
1.2.2
1.2.1
1.2.0
1.1.6
1.1.5
1.1.4
1.1.3
1.1.2
1.1.1
1.1
1.1b2
1.1b1
1.1a2
1.1a1
1.0.4
1.0.3
1.0.2
1.0.1
1.0
1.0b9
1.0b8
1.0b7
1.0b6
1.0b5
1.0b4
1.0b3
1.0b2
1.0b1
Using 1.2.6
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/p/plone.app.theming/plone.app.theming-1.2.6.tar.gz (1.1 MB) for plone.app.theming.
Downloading plone.app.theming
Using cached download
Unpacking plone.app.theming...
done
working in /tmp/tmp3f2QsIconda_skeleton_plone.app.theming-1.2.6.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


Applying patch: '/tmp/tmp3f2QsIconda_skeleton_plone.app.theming-1.2.6.tar.gz/pypi-distutils.patch'
WARNING: Could not add entry points. They were:

    [z3c.autoinclude.plugin]
    target = plone
    
Warning, the following versions were found for plone.app.testing
5.0b4
5.0b3
5.0b2
5.0b1
5.0a2
5.0a1
4.2.5
4.2.4
4.2.3
4.2.2
4.2.1
4.2
4.0.2
4.0.1
4.0
4.0a6
4.0a5
4.0a4
4.0a3
3.0a1
1.0a2
1.0a1
Using 5.0b4
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/p/plone.app.testing/plone.app.testing-5.0b4.tar.gz (80 KB) for plone.app.testing.
Downloading plone.app.testing
Using cached download
Unpacking plone.app.testing...
done
working in /tmp/tmpV2TkdNconda_skeleton_plone.app.testing-5.0b4.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

Applying patch: '/tmp/tmpV2TkdNconda_skeleton_plone.app.testing-5.0b4.tar.gz/pypi-distutils.patch'
Error: Could not parse: plone.testing [zca,security,zodb,z2]
