Error: prefix already exists: /home/ubuntu/miniconda/envs/_pipbuild_
Exception:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/commands/install.py", line 268, in run
    wheel_cache
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/basecommand.py", line 268, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req/req_install.py", line 207, in from_line
    wheel_cache=wheel_cache)
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/req/req_install.py", line 66, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2960, in parse
    reqs = list(parse_requirements(s))
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2904, in parse_requirements
    "version spec")
  File "/home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2869, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'urllib3==>=1.7', 'at', '==>=1.7')

Package search: {'_pypi_ordering': False, 'version': '0.99.5', 'name': 'pyes', 'summary': 'Python Elastic Search driver'}
Creating standard recipe for pyes-0.99.5
Converting recipe in /home/ubuntu/pypi-conda-builds/pyes
package = pyes
   dependencies = [u'urllib3 >=1.7', u'six >=1.5.2']
Creating standard recipe for urllib3->=1.7
Error: Version >=1.7 of urllib3 is not available on PyPI.

conda create -n _pipbuild_ --yes python pip
/home/ubuntu/miniconda/envs/_pipbuild_/bin/pip install urllib3==>=1.7
Error: Could not pip install urllib3==>=1.7
