Warning, the following versions were found for raven
5.3.1
5.3.0
5.2.0
5.1.1
5.1.0
5.0.0
4.2.3
4.2.2
4.2.1
4.2.0
4.1.1
4.1.0
4.0.4
4.0.3
4.0.2
4.0.1
4.0.0
3.6.1
3.6.0
3.5.2
3.5.1
3.5.0
3.4.1
3.4.0
3.3.12
3.3.11
3.3.10
3.3.9
3.3.8
3.3.7
3.3.6
3.3.5
3.3.4
3.3.3
3.3.2
3.3.1
3.3.0
3.2.1
3.2.0
3.1.17
3.1.16
3.1.15
3.1.13
3.1.12
3.1.11
3.1.10
3.1.9
3.1.8
3.1.7
3.1.6
3.1.5
3.1.4
3.1.3
3.1.2
3.1.1
3.1.0
3.0.1
3.0.0
2.0.12.3
2.0.12.2
2.0.12.1
2.0.12
2.0.11
2.0.10
2.0.9
2.0.8
2.0.7.1
2.0.7
2.0.6
2.0.5
2.0.4
2.0.3
2.0.2
2.0.1
2.0.0
1.9.4
1.9.3
1.9.2
1.9.1
1.9.0
1.8.4
1.8.3
1.8.2
1.8.1
1.8.0
1.7.7
1.7.6
1.7.5
1.7.4
1.7.3
1.7.2
1.7.1
1.7.0
1.6.1
1.6.0
1.5.0
1.4.6
1.4.5
1.4.4
1.4.3
1.4.2
1.4.1
1.4.0
1.3.6
1.3.5
1.3.3
1.3.2
1.3.1
1.3.0
1.2.2
1.2.1
1.2.0
1.1.6
1.1.5
1.1.4
1.1.3
1.1.2
1.1.1
1.0.4
0.7.1
0.7.0
0.6.1
0.6.0
0.5.1
0.5
0.4
0.3
0.2
0.1
Using 5.3.1
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/r/raven/raven-5.3.1.tar.gz (312 KB) for raven.
Downloading raven
Using cached download
Unpacking raven...
done
working in /tmp/tmpAWZ4zpconda_skeleton_raven-5.3.1.tar.gz
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.1. Run

conda update -n root conda-build

to get the latest version.


The following NEW packages will be INSTALLED:

    numpy:  1.9.2-py27_0
    pyyaml: 3.11-py27_1 
    yaml:   0.1.6-0     

Linking packages ...
[                    ]|                                                  |   0%[yaml                ]|                                                  |   0%[numpy               ]|################                                  |  33%[pyyaml              ]|#################################                 |  66%[      COMPLETE      ]|##################################################| 100%
Applying patch: '/tmp/tmpAWZ4zpconda_skeleton_raven-5.3.1.tar.gz/pypi-distutils.patch'
Warning, the following versions were found for unittest2
1.1.0
1.0.1
1.0.0
0.8.0
0.7.1
0.7.0
0.6.0
0.5.1
0.5.0
0.4.2
0.4.1
0.4.0
0.3.0
0.2.0
0.1.6
0.1.5
0.1.4
0.1.3
0.1.2
0.1.1
0.1.0
0.0
Using 1.1.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/u/unittest2/unittest2-1.1.0.tar.gz (80 KB) for unittest2.
Downloading unittest2
Using cached download
Unpacking unittest2...
done
working in /tmp/tmptfd9Lcconda_skeleton_unittest2-1.1.0.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.



Applying patch: '/tmp/tmptfd9Lcconda_skeleton_unittest2-1.1.0.tar.gz/pypi-distutils.patch'
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-skeleton", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_skeleton.py", line 240, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 349, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_skeleton.py", line 254, in execute
    pypi.main(args, parser)
  File "/home/ubuntu/conda-build/conda_build/pypi.py", line 387, in main
    get_package_metadata(args, package, d, data)
  File "/home/ubuntu/conda-build/conda_build/pypi.py", line 486, in get_package_metadata
    pkginfo = yaml.load(fn)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 93, in construct_object
    data = generator.next()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 568, in construct_python_object
    instance = self.make_python_instance(suffix, node, newobj=True)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 540, in make_python_instance
    cls = self.find_python_name(suffix, node.start_mark)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 513, in find_python_name
    module.__name__), mark)
yaml.constructor.ConstructorError: while constructing a Python object
cannot find 'late_version' in the module '__main__'
  in "/tmp/tmptfd9Lcconda_skeleton_unittest2-1.1.0.tar.gz/pkginfo.yaml", line 20, column 10
