Package search: {'_pypi_ordering': False, 'version': '0.1.2', 'name': 'wsgiref', 'summary': 'WSGI (PEP 333) Reference Library'}
Creating standard recipe for wsgiref-0.1.2
Using url https://pypi.python.org/packages/source/w/wsgiref/wsgiref-0.1.2.zip (36 KB) for wsgiref.
Downloading wsgiref
Using cached download
Unpacking wsgiref...
done
working in /tmp/tmpOQscAJconda_skeleton_wsgiref-0.1.2.zip
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.0. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

---------------------------------------------------------------------------
This script requires setuptools version 0.6b3 to run (even to display
help).  I will attempt to download it for you (from
http://cheeseshop.python.org/packages/2.7/s/setuptools/), but
you may need to enable firewall access for this script first.
I will start the download in 15 seconds.

(Note: if this machine does not have network access, please obtain the file

   http://cheeseshop.python.org/packages/2.7/s/setuptools/setuptools-0.6b3-py2.7.egg

and place it in this directory before rerunning this script.)
---------------------------------------------------------------------------
Downloading http://cheeseshop.python.org/packages/2.7/s/setuptools/setuptools-0.6b3-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    ez_setup.use_setuptools()
  File "/tmp/tmpOQscAJconda_skeleton_wsgiref-0.1.2.zip/wsgiref-0.1.2/ez_setup/__init__.py", line 70, in use_setuptools
    egg = download_setuptools(version, download_base, to_dir, download_delay)
  File "/tmp/tmpOQscAJconda_skeleton_wsgiref-0.1.2.zip/wsgiref-0.1.2/ez_setup/__init__.py", line 124, in download_setuptools
    src = urllib2.urlopen(url)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/home/ubuntu/miniconda/envs/_build/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error: prefix already exists: /home/ubuntu/miniconda/envs/_pipbuild_
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in /home/ubuntu/miniconda/envs/_pipbuild_/lib/python2.7
Traceback (most recent call last):
  File "__tmpfile__.py", line 1, in <module>
    import pkg_resources;
ImportError: No module named pkg_resources
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Error 404: Not Found

Applying patch: '/tmp/tmpOQscAJconda_skeleton_wsgiref-0.1.2.zip/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpOQscAJconda_skeleton_wsgiref-0.1.2.zip/wsgiref-0.1.2
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install

conda create -n _pipbuild_ --yes python pip
/home/ubuntu/miniconda/envs/_pipbuild_/bin/pip install wsgiref==0.1.2
Getting dependencies...
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-pipbuild", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 80, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 349, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 360, in execute
    build_package(package, version, noarch_python=args.noarch_python)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 304, in build_package
    noarch_python=noarch_python)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 240, in make_recipe
    depends = get_all_dependencies(package, version)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 219, in get_all_dependencies
    output = subprocess.check_output(cmd3args)
  File "/home/ubuntu/miniconda/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/home/ubuntu/miniconda/envs/_pipbuild_/bin/python', '__tmpfile__.py']' returned non-zero exit status 1
