Error: prefix already exists: /home/ubuntu/miniconda/envs/_pipbuild_
Collecting ZODB3==3.11.0
  Downloading http://localhost/packages/source/Z/ZODB3/ZODB3-3.11.0.tar.gz (55kB)
setuptools must be installed to install from a source distribution
Package search: {'_pypi_ordering': False, 'version': '3.10.5', 'name': 'ZODB3', 'summary': 'Zope Object Database: object database and persistence'}
Creating standard recipe for zodb3-3.11.0
Using url https://pypi.python.org/packages/source/Z/ZODB3/ZODB3-3.11.0.tar.gz (54 KB) for ZODB3.
Downloading ZODB3
Using cached download
Unpacking ZODB3...
done
working in /tmp/tmpyeEbt4conda_skeleton_ZODB3-3.11.0.tar.gz
Fetching package metadata: ......

WARNING: conda-build appears to be out of date. You have version 1.13.0 but the
latest version is 1.14.0. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    from setuptools import setup
ImportError: No module named setuptools

Applying patch: '/tmp/tmpyeEbt4conda_skeleton_ZODB3-3.11.0.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpyeEbt4conda_skeleton_ZODB3-3.11.0.tar.gz/ZODB3-3.11.0
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install

conda create -n _pipbuild_ --yes python pip
/home/ubuntu/miniconda/envs/_pipbuild_/bin/pip install ZODB3==3.11.0
Error: Could not pip install ZODB3==3.11.0
